#!/bin/bash


function theme {
  local shell_color_conf="$HOME/.bashbg"
  local vim_color_conf="$HOME/.vimbg"

  local default_name="default-dark"

  local name="${1:-$(echo $default_name)}"
  local base="$HOME/.config/base16-shell/scripts/"
  local prfx="base16-"
  local sufx=".sh"

  local them=${prfx}${name}
  local file=${base}${them}${sufx}

  # Verbose
  echo "vim"
  echo "  |__ conf        $vim_color_conf"
  echo "  |__ theme       $them"
  echo "shell"
  echo "  |__ conf        $shell_color_conf"
  echo "  |__ theme       $file"

  # Set bash colors
  echo "source $file" > $shell_color_conf
  source $shell_color_conf

  # Set vim colors
  echo "colorscheme $them" >> $vim_color_conf
}


# Switch theme
theme $1

